### ISSUE TITLE
WM/LZ von Fernkampfwaffen

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#10]
Schusswaffen wie z.B. Bögen können laut s. 66 Holzbearbeitung zu einer Pers. Waffe (-8, WM+1) gemacht werden.

In Sephrasto ist es nicht möglich den WM einer Fernkampfwaffe zu verändern, ohne dabei auch die Ladezeit LZ zu verändern. Es wird das gleiche Feld benutzt. Im PDF kann das ganze auch nicht einzeln eingetragen werden.

Vorschlag: In Sephrasto die 'WM' Box da lassen wo sie ist und eine zusätzliche modale Box 'LZ' für Fernkampfwaffen einblenden. Im PDF dann WM/LZ mit einem Schrägstrich eintragen z.B. 1/1 oder +1/1 für einen Persönlichen Elfenbogen.

Gleiches Problem auch bei Armbrüsten s. 66

**Comment by Alchemist650** [comment]
In v2, auf Seite 62, existiert die Persönliche Waffe immernoch.

Im Regeleditor (1.1.0) gibt es auch weiterhin Möglichkeit den WM des Bogens (oder anderer Schusswaffen) zu verändern.

**Comment by brzGatsu** [comment]
In der Charakterausrüstung kannst du den WM in 1.1.0 separat anpassen. Im Datenbank-Editor fehlt die Möglichkeit noch.

**Comment by Alchemist650** [comment]
Ich sehs, danke :-)
