### ISSUE TITLE
Textfeld für Waffen TP nicht mehr editierbar

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#21]
Version 0.6.1, aktueller git pull,
Manjaro
Python 3.7.0

Waffen können hinzugefügt werden, aber die Anzahl W6 und den zusätzlichen +Schaden kann nicht eingetragen oder überhaupt gesehen werden (siehe Screenshot)

![screenshot_20180829_202352](https://user-images.githubusercontent.com/10513428/44807329-8bfa1a00-abc9-11e8-9f17-61e8245197a4.png)

**Comment by Alchemist650** [comment]
Fehler besteht unter 1.1.0 weiterhin.

**Comment by brzGatsu** [comment]
Auf anderen Plattformen haben wir das Problem (bisher) nicht. Ich habe leider nur Zeit bei der Windows-Version zu helfen.

**Comment by Alchemist650** [comment]
Ja, der aktueller pull auf 1.5.3 hat es gefixed!

![Screenshot_20220106_220211](https://user-images.githubusercontent.com/10513428/148451663-f35694f6-230e-4299-9c4e-b53ef6c1cbf9.png)
