### ISSUE TITLE
PDF Erstellung fehlgeschlagen

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#24]
Betriebssystem: Manjaro KDE
Sephrasto Version: 0.6.1 (vor jedem Start über git pull aktualisiert)
python --version: Python 3.7.0
pdftk --version: pdftk 2.02 aus AUR installiert

Sephrasto startet normal, Charaktere können normal erstellt werden, wird der PDF erstellen Knopf gedrückt und ein Speicherpfad gewählt kommt Fehlercode :0, Fehlermeldung: No Error, You really shouldnt be seeing this.

;-)

PDF wird leider nicht erstellt.

sephrasto.log:
2018-10-20 23:59:30,910 | CRITICAL | Sephrasto.py::__init__(60) | Starte Sephrasto v0.6.1
2018-10-20 23:59:46,601 | ERROR | CharakterEditor.py::pdfButton(268) | Sephrasto Fehlercode 0. Exception: local variable 'check' referenced before assignment

**Comment by Alchemist650** [comment]
Das gleiche passiert auch auf zwei unterscheidlichen Windows PCs und zwar immer dann, wenn in den Einstellungen "Welcher Charakterbogen soll verwendet werden?" "Standard Ilaris-Charakterbogen" angegeben wird. Wählt man "Frag immer nach" funktioniert die PDF Generierung wieder.

Gruss
Alchemist

**Comment by brzGatsu** [comment]
Tritt der Fehler noch auf? Kann ich in 1.1.0 nicht reproduzieren.

**Comment by Alchemist650** [comment]
Betriebssystem: Manjaro KDE
Sephrasto Version 1.1.0
pdftk ist 2.0.2 aus dem AUR installiert
python 3.7.3

In den Sephrasto Einstellungen habe ich unter Export-Plugin /bin/pdftk angegeben (danach Sephrasto neugestartet)

Fehlermeldung beim Speichern als PDF:
```
Beim Erstellen des Charakterbogens ist ein Fehler aufgetreten.
Fehlercode: -81
Fehlermeldung: PDFtk-Error: The empty Charactersheet could not be loaded. Is PDFtk installed and working; have you restarted Sephrasto; and is the selected Character sheet a valid empty Charactersheet? Note that if you have a file called Charakterbogen.pdf in your Sephrasto folder that is not an empty character sheet, the export may not work or produce unforeseen results. PDFtk can be obtained at  [...]
```

In der Konsole desweiteren:
```
kf5.kio.core: We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nError loading services.\n"
kf5.kio.core: We got some errors while running 'net usershare info'
kf5.kio.core: "Can't load /etc/samba/smb.conf - run testparm to debug it\n"
kf5.kio.widgets: No node found for item that was just removed: QUrl("file:///home/christoph/Qsync/Ilaris/Charaktere/Andergasterin.xml")
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 9327, resource id: 38468961, major code: 40 (TranslateCoords), minor code: 0
```
Wobei anzumerken wäre, dass der Pfad /home/christoph/Qsync/Ilaris/Charaktere/ mein vorderfinierter Ordner für Charaktere ist und Andergasterin.xml die oberste Datei in diesem Verzeichnis. Verschiebt man die Datei ergibt sich die Fehlermeldung erneut mit der obersten.

**Comment by brzGatsu** [comment]
Das ist ein anderer Fehler, dürfte der gleiche sein wie der hier: https://github.com/Aeolitus/Sephrasto/issues/27

Ist mit diesem commit gefixt, muss nur noch gemerged werden: https://github.com/brzGatsu/Sephrasto/commit/9cb667f6cf7303433890c31a8cd1a67cf951c61d

**Comment by Alchemist650** [comment]
Auf Windows läuft es, auch der Bug dass bei der expliziten Angabe in den Einstellungen die PDF nicht generiert wird ist behoben.

Wenn der merge durch ist, mach ich ein pull auf der Linuxkiste und melde mich wieder.

**Comment by Aeolitus** [comment]
Ist reingemerged und sollte gefixt sein
