### ISSUE TITLE
PDF Erstellung unter MacOS X, Argument "startupinfo" an subprocess.check_output erzeugt Fehler 81

### ISSUE THREAD

**Issue by suermeli** [Aeolitus/Sephrasto#27]
Hallo, vielen Dank für das absolut praktische Tool! 

In der aktuellen Version habe ich ein Problem bei der PDF-Erstellung unter Mac OS X, die ich zuerst für einen Fehler mit pdftk hielt. Der Fehler tritt auf, wenn ich das PDF erstellen möchte -- unabhängig von der gewählten Charakterbogen-Version. Ich habe auch bereits die vorgefertigten Bögen mit git wieder zurückgesetzt (für den Fall des Falles) etc. Es kommt immer Fehler 81. 

Ich habe daraufhin mal in den Quelltext geschaut, das Problem tritt in "check_output_silent" in pdf.py nach Ruf aus der Methode "get_fields" auf. Das Problem scheint "startupinfo=startupinfo" in der letzten Zeile von "check_ouput_silent" zu sein. ich vermute, es liegt daran, dass die startupinfo-Variable ja nur initialisiert wird, falls die Plattform Windows ist. Ich denke, dass man entweder die Zeile "startupinfo = subprocess.STARTUPINFO()" vor die IF-Abfrage bewegen müsste oder im Else-Fall einfach das startupinfo-Argument leer lassen müsste. 

Jedenfalls hilft bei mir unter MacOS X das Entfernen des "startupinfo=startupinfo",um as Problem zu lösen. 

Insgesamt ist das Verfahren etwas verwirrend, dass ein Fehler mit pdftk suggeriert wird, obwohl die 81 ja nur sagt "also get_fields war der letzte Call, den ich abgesetzt habe". 

Hoffe, das hilft. :)

**Comment by Aeolitus** [comment]
Ist gefixt, danke für den Hinweis (und danke an Gatsu fürs fixen)
