### ISSUE TITLE
Härte bei Waffen ist auf 20 gecappt

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#30]
Die Härte bei Waffen ist bei 20 gecappt, selbst wenn eine neue Waffe über die Regelbasis mit einer Härte > 20 hinzugefügt wird.

Im Schmiedekapitel wird darauf verwiesen dass Endurium 100% schon allein +16 Härte mitbringt. Es kann also gut möglich sein, dass die Härte über 20 steigt.

**Comment by Aeolitus** [comment]
Im neuesten Commit gefixt
