### ISSUE TITLE
Als Gildenmagier(Srl,Geo...) sind gewisse Zauber unter Dämonisch verfügbar, die nicht verfügbar sein sollten

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#34]
Brenne toter Stoff
Hartes Schmelze
Weiches erstarre

Siehe unter dem Punkt Fertikeiten dieser drei Zauber.

**Comment by brzGatsu** [comment]
Danke für den Fehlerbericht, du hast recht. Unterschiedliche Voraussetzungen für einzelne Fertigkeiten lassen sich derzeit leider nicht vernünftig in Sephrasto umsetzen, ich denke eher nicht, dass es den Arbeitsaufwand wert wäre.

**Comment by brzGatsu** [comment]
Habe es über einen workaround realisiert, indem ich die Zauber dupliziert habe mit entsprechend unterschiedlichen Voraussetzungen. Im Falle einer Doppeltradition (z.B. Mag, Bor) erscheinen die Zauber nun zweimal, da sollte entsprechend dann die Dämonisch-Variante mit Zugriff über alle Fertigkeiten gewählt werden.
