### ISSUE TITLE
Feature Request: Aktuelle AsP/KaP im Attribute Tab anzeigen

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#35]
Hallo,

Die Entscheidung wieviel AsP/KaP zugekauft werden hängt oft davon ab wieviel man schon hat.
Hinter den Boxen für Zugekaufte Astralenergie/Karmaenergie könnte die aktuelle AsP/KaP Zahl stehen die durch Vorteile und bereits gekaufte Punkte zusamman kommt. Und damit die Entscheidung vereinfachen.

Vorteile die dabei zu beachten sind: Zauberer I-IV, Gefäss der Sterne (und damit CH), Geweiht I-IV und Paktierer I-IV.

Evtl. könnte die leere Zeile im gleichen Zug genutzt werden um auch GuP zu verwalten?

Schönes Wochenende
Alchemist650

**Comment by brzGatsu** [comment]
Danke für den Vorschlag. GuP waren ja schon länger drin, die Anzeige der aktuellen AsP/KaP ist nun in der nächsten Version.
