### ISSUE TITLE
PDF-Erstellung fehlgeschlagen

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#36]
Bei mir hat sich gegenüber vorher zu issue #24 nur der Fehlercode von -81 auf -99 geändert.

> Beim Erstellen des Charakterbogens ist ein Fehler aufgetreten.
> Fehlercode: -99
> Fehlermeldung: Error when trying to execute export plugin

Gruss
Alchemist650

**Comment by Alchemist650** [comment]
Ich hatte heute ein bisschen Zeit und das Problem weiter zu erforscht. Im Sephrasto.log in den DEBUG messages gibt es einen Hinweis auf pdfMeister.py line 690 - invalid syntax.

Dort wird `exec(open(Wolke.Settings['Pfad-Export-Plugin'], mode="r", encoding="utf-8").read(), api)` aufgerufen.

print(Wolke.Settings['Pfad-Export-Plugin']) gibt /bin/pdftk zurück.

Wenn ich Zeile 93-95 in pdfMeister.py auskommentiere bekomme ich logischerweise den syntax error nicht zu spüren, die PDF generierung läuft durch und wird erstellt. Einzig dass öffnen des PDFs wird nicht durchgeführt (Fehler -98), aber damit kann ich leben.

Für was genau ist also dieser call und warum gibt es einen Syntax error?

Gruss
Alchemist650

**Comment by brzGatsu** [comment]
Das Export-Plugin ist ein Python file das du in den Sephrasto-Einstellungen setzen kannst. Damit kannst du nachträglich die PDF-Felder anpassen und du hast Zugriff auf die Vorteil-Script-API Get-Funktionen. Wenn das wie bei dir kein Pfad zu einer Python-Datei ist wird das wohl einen Fehler werfen, ich kann das beizeiten mal etwas sicherer machen.

**Comment by Alchemist650** [comment]
In meinen Einstellungen zum Speicherpfad für Export-Plugin steht: /bin/pdftk

An der Stelle ist auch tatsächlich ein binary:
/bin/pdftk --version
pdftk port to java 3.1.3 a Handy Tool for Manipulating PDF Documents
Copyright (c) 2017-2018 Marc Vinyals - https://gitlab.com/pdftk-java/pdftk
Copyright (c) 2003-2013 Steward and Lee, LLC.
pdftk includes a modified version of the iText library.
Copyright (c) 1999-2009 Bruno Lowagie, Paulo Soares, et al.
This is free software; see the source code for copying conditions. There is
NO warranty, not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Habe ich dass falsch verstanden und dort kommt nicht der Pfad für pdftk hin?

Beste Grüsse
Alchemist650

**Comment by brzGatsu** [comment]
Sorry für die späte Antwort, ja falsch verstanden :-) Der Pfad in den Einstellungen sollte nur gesetzt werden, wenn du ein eigenes Plugin hast, das den Export-Prozess modifiziert.

**Comment by Alchemist650** [comment]
Funktioniert mit 1.5 einwandfrei.
