### ISSUE TITLE
Waffen Trefferwürfel bei 9W6 gecappt

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#37]
Ich wollte die überschwere Rotze von Ilaris Advance als tatsächliche Waffe einfügen, da wir in unserer Spielrunde stationäre Geschütze zur Verfügung haben.

Die Überschwere Rotze hat in IA 11W6, im Regelbasis Editor sind Waffen allerdings bei 9W6 gecappt.

Grüsse
Alchemist

**Comment by Aeolitus** [comment]
Im nächsten Release gefixt, danke
