### ISSUE TITLE
Auf welchen System läuft Sephrasto

### ISSUE THREAD

**Issue by EranTheMerchant** [Aeolitus/Sephrasto#44]
Erstens: vielen Dank für dieses wunderbare Programm!!! Die Funktion Hausregeln erstellen zu können, ist einfach Klasse.  
Zweitens: kenne mich mit Phyton null aus. Läuft das Programm auch auf Macbooks (ARM-Chip) oder ARM-Windows, Bisher nur Windows probiert, aber Laptopwechsel steht an und würde Sephrasto gerne weiternutzen.

**Comment by brzGatsu** [comment]
Hi, Sephrasto basiert auf Python, Qt und für den Export pdftk. Solange das von deiner Prozessor-Architektur und deinem Betriebssystem unterstützt wird sollte Sephrasto laufen. Selbst wenn es nicht auf ARM läuft: Soweit ich weiß können ARM-Mac und Windows x86/64 emulieren und sind damit voll kompatibel mit allen Programmen, aber ich kann es nicht testen und damit nicht garantieren. Schau mal in den Sephrasto-Thread auf dsaforum.de, da gibt es Macnutzer die du kontaktieren könntest.
