### ISSUE TITLE
Sephrasto kann Datenbank/Regelbasis nicht laden wenn es ausserhalb des Ordners ausgeführt wird

### ISSUE THREAD

**Issue by daoert** [Aeolitus/Sephrasto#46]
Wenn ich auf Linux die Sephrasto.py ausserhalb des Ordners ausführe, also zum Beispiel ’python /home/Name/Sephrasto/Sephrasto.py’ ausführe im Terminal, dann werden die Datenbanken/Regelbasen nicht geladen. Nur wenn ich vorher in den Ordner navigiere und dann ’python Sephrasto.py’ ausführe werden die Datenbanken geladen.
Ein Freund von mir meinte auch, dass wenn man Sephrasto über die Windowssuche ausführt, die Datenbank/Regelbasis nicht geladen wird, aber wenn man es über eine Verknüpfung ausführt schon.

**Comment by brzGatsu** [comment]
Hi, danke für den PR. Sephrasto damit noch nicht rund - nur auf den Ersten Blick: das Icon wird nicht geladen, die PDF-Erstellung schlägt fehl, Plugins aus dem Installationsordner werden nicht geladen. Falls du das noch beheben möchtest gerne, aber bis dahin würde den Fix eher nicht einspielen, da das Problem aktuell nur verzögert wird und wir betroffenen Usern dadurch gegebenenfalls schlechter helfen können. Bis zu einem vollständigen fix wäre es evtl auch sinnvoll direkt bei Start eine Fehlermeldung anzuzeigen, falls Sephrasto nicht aus dem Installordner gestartet wird...
