### ISSUE TITLE
Datenbank redundanz

### ISSUE THREAD

**Issue by XaverStiensmeier** [Aeolitus/Sephrasto#48]
In der Datenbank existiert genau einmal innerhalb einer Kategorie (Waffeneigenschaft) zwei gleiche Einträge, wenn man das erste Zeichen klein schreibt: "nicht für ..." "Nicht für ...".

Eine solche Dopplung sollte vermieden werden. Man kann sie vermeiden, indem man alle Zugriffe auf "Nicht für ..." durch firstCap("nicht für ...") ersetzt und die Funktion einfügt:
`def firstCap(s):
  if len(s) > 0:
    s = s[0].upper() + s[1:]
  return s`

**Warum ist das für mich interessant?**
Aktuell erstelle ich automatisch aus der Datenbank ein LaTeX-Glossar. Ich habe mich entschieden, dass alle id's klein anfangen. Dadurch, dass die Einträge sich jedoch nur in der Groß-/Kleinschreibung des Erstbuchstabens unterscheiden, muss ich das danach immer anpassen oder extra dafür einen Ausnahmefall schreiben.

Das ist aber nur eine Erklärung, warum ich mich damit befasst habe. Das Unästhetische sollte im Vordergrund stehen.

**Comment by brzGatsu** [comment]
Danke für den report. Die "Waffeneigenschaft" wurde wohl in Ilaris 2 eh umbenannt und wird - falls an erster Stelle - nicht mehr groß geschrieben, daher reichte eine reine Datenbankanpassung als Fix.
