### ISSUE TITLE
Zusätzliches Farbschema?

### ISSUE THREAD

**Issue by lukruh** [Aeolitus/Sephrasto#54]
Wollte mir auch mal PyQt anschauen und hab einfach mal etwas mit den UI Farben rumgespielt und es kam dem Design des DSA Forums recht nah ;)

![image](https://user-images.githubusercontent.com/7965770/149601321-5337d3e4-cec1-4216-a4ed-89954e750c08.png)

Habs bei mir einfach mal als drittes Theme mit rein gepackt, falls erwünscht, kann ich da noch die restlichen elemente anpassen und nen PR erstellen?

**Comment by brzGatsu** [comment]
Gerne, sieht gut aus!

**Comment by brzGatsu** [comment]
Danke für deinen commit!

**Comment by brzGatsu** [comment]
FYI ich habe gerade nochmal ein paar kleine Änderungen am Style gemacht. Insbesondere die stylesheet overrides für die widgets scheint (zumindest auf windows) der fusion style garnicht zu mögen. Ich denke es sieht ohne die overrides aber immernoch top aus. Die Textfarbe habe ich noch überall auf schwarz gestellt, damit es besser lesbar ist.
