### ISSUE TITLE
Installationsanweisungen aktualisieren

### ISSUE THREAD

**Issue by Skillmon** [Aeolitus/Sephrasto#56]
Für die beschriebene Linux-Installation fehlt die Datei requirements.txt. So muss man dann eben sehen, welche Python-Bibliotheken alles fehlen (`pipreqs`).

**Comment by lukruh** [comment]
im letzten PR (https://github.com/Aeolitus/Sephrasto/pull/55) wurde die requirements durch poetry ersetzt, ich denke 1-2 Hinweise dazu in der Readme.md wären hilfreich und eventuell, kann die requirements.txt trotzdem bleiben oder irgendwie mitgebaut werden? Da pip vermutlich für die meisten der gewohnte weg ist python module zu verwalten und man kein extra tool installieren muss.

**Comment by brzGatsu** [comment]
Fixed in https://github.com/Aeolitus/Sephrasto/commit/79e48c7ef18c7574024fe383ee78f67ed09aba8b

**Comment by dbuse** [comment]
Klingt sinnig. Die `requirements.txt` kann man übrigens recht einfach von poetry exportieren lassen: https://python-poetry.org/docs/cli/#export

Ich schaue demnächst mal, wie ein Pfad Richtung via `pip` installierbarer Distribution von Sephrasto einschlagen ließe -- also ganz ohne git checkout usw.
