### ISSUE TITLE
Ordner- / Projektstruktur

### ISSUE THREAD

**Issue by lukruh** [Aeolitus/Sephrasto#60]
Ich finds persönlich relativ unübersichtlich so viele Dateien direkt im Projektordner zu haben. Insbesondere wenn die pyqt gebauten Dateien auchnoch mitten drin liegen. Ein paar Unterordner wenigstens die klassichen `src`, `res` und `build` ordner oder so fände ich praktisch um a) schneller die richtigen Dateien zu finden und b) um direkt manche ordner über die .gitignore aus den commits herauszuhalten.

**Comment by brzGatsu** [comment]
Da hast du recht, ist mittlerweile zu viel geworden.

**Comment by dbuse** [comment]
Ganz eurer Meinung. Außerdem ist es momentan gefährlich, aus dem repo ein wheel oder sdist zu bauen und zu installieren, weil alle Dateien dann direkt im `site-packages` verzeichnis landen und da mit anderen Paketen kollidieren können.
Idealerweise gehören automatische Artefakte, also alles was aus einem Compiler wie dem QT-Konverter der aus `.ui` files `.py` files macht, irgendwohin weggeräumt. Wenn nicht sogar ganz aus dem git verbannt und bei Bedarf neu gebaut.

Bleibt die Frage, wie es final aussehen soll. Für Libraries orientiere ich mich hier dran: <https://blog.ionelmc.ro/2014/05/25/python-packaging/>. Aber das ist explizit für libraries, nicht applications. Und Sephrasto ist ja nun eindeutig letzteres.

**Comment by brzGatsu** [comment]
Ich hätte nun folgende Struktur:
- build
- designer
   - *.ui files
- src
  - Sephrasto
    - Bin/Data/Plugins wie bisher
    - Data
      - *.pdf files und database.xml
    - UI
       - aus .ui files generierte .py files
    - *.py files
    - icons
    - .sln und .pyproj
- build.bat
- gitignore
- license
- poetry files, requirements.txt
- readme
- reference.pdf

Was haltet ihr davon?
