### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by lukruh** [Aeolitus/Sephrasto#61]
hey, bei einem unserer Spieler, kam es zu einer Fehlermeldung beim Ausführen unter Windows, eine log file scheint garnicht erst erstellt zu werden. Gibt es noch etwas was beachtet werden muss? Muss vorher python bzw. PyQT extra installiert werden oder ähnliches? Ich bin leider absoluter Windowsnoob und wüsste jetzt so nicht, wie ich das weiter debuggen könnte.

![image](https://user-images.githubusercontent.com/7965770/152198144-8fd5230e-b399-403d-b522-f3c72a840e4f.png)

Der Fehler trat bei allen 3 letzten releases auf 1.5.2, 1.6 und 1.7.

**Comment by lukruh** [comment]
Hm ist auf jedenfall die gepackte .exe gewesen aus den releases. Er hats mir nochmal via screenshare demonstriert. Auch mit deaktiviertem Antivirusprogramm kam der selbe Fehler. Bei allen anderen startete es problemlost, ist also ein Einzelfall.

**Comment by lukruh** [comment]
Im Internet bin ich darüber gestolpert:
https://cx-freeze.readthedocs.io/en/latest/faq.html#microsoft-visual-c-redistributable-package
besagte DLLs sind oft bereits vorhanden, aber nicht standardmäßig vorinstalliert. könnte es sich evt darum handeln?

Im Pfad der Fehlermeldung ist mir aufgefallen, dass `python37_64` für mich auf ne 64bit anwendung hinweist, `Program Files (x86)` sollte vom Namen her aber für Programme auf 32bit ausgelegt sein oder? (Sorry falls das ne dumme Idee ist hab seit vielen Jahren kein Windows mehr angefasst.)

**Comment by brzGatsu** [comment]
Vc runtime könnte sein, qt braucht die und wir liefern sie nicht mit. Wenn er mag kann er mal schauen, obs damit klappt: https://www.microsoft.com/de-de/download/details.aspx?id=53840

Der Pfad ist kein Problem, das ist nur meine vs installation, gibts nur in 32 bit.
